- type: EventHub
  eventTypes:
  - SensorChange
  - UdfCustom
  connectionString: PrimaryConnection;EntityPath=eventhubtwin
  secondaryConnectionString: SecondaryConnection;EntityPath=eventhubtwin
  path: eventhubtwin
