- name: Parking places
  type: Venue
  resources:
  - type: IoTHub
  spaces:
  - name: Space 1
    type: Space
    spaces:
    - name: Area A
      type: Area
    - name: Place 1
      type: Place
      subType: Paid
    - name: Place 2
      type: Place
      subType: Free
      devices:
      - name: Raspberry Pi 3 A1
        hardwareId: 1234567890AB
        sensors:
        - dataType: Motion
          hardwareId: SAMPLE_SENSOR_MOTION
      matchers:
      - name: Matcher Motion A1
        dataTypeValue: Motion
      userdefinedfunctions:
      - name: Motion Processor
        matcherNames:
        - Matcher Motion A1
        script: config/udf/availability.js
      roleassignments:
      - roleId: 98e44ad7-28d4-4007-853b-b9968ad132d1 # System Role: SpaceAdministrator
        objectName: Motion Processor
        objectIdType: UserDefinedFunctionId
